# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
warnings_are_errors: false
sudo: required
cache: packages
dist: trusty

notifications:
  email:
    on_success: change
    on_failure: change

r_github_packages:
  - r-lib/covr

after_success:
  - Rscript -e 'covr::codecov()'
